services:
  app:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    restart: unless-stopped
    container_name: darms-fortresses
    expose:
      - "80"

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    container_name: darms-tunnel
    command: tunnel --no-autoupdate --url http://app:80
    depends_on:
      - app
